[terminal.shell]
program="/usr/bin/fish"

[window]
decorations="None"

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
size = 15

[general]
import = [
	"~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

