[terminal.shell]
program="/usr/bin/fish"

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[window]
decorations="None"
startup_mode="Maximized"

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
size = 15

[general]
import = [
	"~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

